# Generated by Django 5.0.11 on 2026-03-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
                'ordering': ['-name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('reg_no', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Student`s Registration Number')),
                ('phone_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Student`s Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Student`s Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Candidate`s Name')),
                ('image', models.ImageField(upload_to='media/candidates/')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voter.post', verbose_name='Candidate`s Position')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
