# Generated by Django 5.0.11 on 2026-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student`s Phone Number'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Student`s Registration Number'),
        ),
    ]
