# Generated by Django 5.0.11 on 2026-03-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0002_alter_voter_phone_number_alter_voter_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Voter`s Email Address'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Voter`s Phone Number'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Voter`s Registration Number'),
        ),
    ]
